spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        globally_quoted_identifiers: true
        enable_lazy_load_no_trans: true
  #        format_sql: true
  data:
    rest:
      base-path: /api/v1
  # If something weird happens in request mapping, you may need to uncomment this.
  resources:
    add-mappings: false
  profiles:
    include: etc

logging:
  level:
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

server:
  port: 8981
  error:
    path: /api/v1/error