spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/hemeijia_dev?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: root
    password: HIThemeijia-dev!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
        globally_quoted_identifiers: true
        search:
          default:
            directory_provider: filesystem
            indexBase: /tmp
        enable_lazy_load_no_trans: true
  data:
    rest:
      base-path: /api/v1
  # If something weird happens in request mapping, you may need to uncomment this.
  resources:
    add-mappings: false
  profiles:
    include: etc

logging:
  level:
    web: DEBUG
    org:
      hibernate:
        SQL: INFO

server:
  port: 8981
  error:
    path: /api/v1/error