site_name: Hemeijia
site_url: https://github.com/YanzheL/hemeijia
repo_url: https://github.com/YanzheL/hemeijia
site_description: Hemeijia
site_author: Yanzhe Lee
edit_uri: ""
theme:
  name: rtd-dropdown
  # name: material
  # name: ivory
  # highlightjs: true
  # hljs_languages:
  #   - yaml
  #   - django
  #   - json
plugins:
  - search
  - git-revision-date
markdown_extensions:
  - smarty
  - toc:
      permalink: True
  - admonition
  - def_list
  - mdx_gh_links:
      user: mkdocs
      repo: mkdocs